In [2]:
import pandas as pd

In [3]:
customers = pd.read_csv('../datasets/raws/customers/customers.csv')
customers.head()

,CustomerID,FullName,Age,AgeBand,IncomeMonthly,IncomeBand,City,RegionCode,Persona,RiskSegment
0,1,Chris King,27,25–34,2581,£2.5–4k,London,E12000007,grad,Medium
1,2,Morgan Jones,55,55–64,1053,£0–1.5k,Newcastle,E12000001,student,High
2,3,Luca Murphy,44,35–44,1103,£0–1.5k,Manchester,E12000002,student,Low
3,4,Ava Jones,54,45–54,1140,£0–1.5k,Manchester,E12000002,student,High
4,5,Sam King,43,35–44,3810,£2.5–4k,Newcastle,E12000001,family,High

In [4]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     300 non-null    int64
 1   FullName       300 non-null    object
 2   Age            300 non-null    int64
 3   AgeBand        300 non-null    object
 4   IncomeMonthly  300 non-null    int64
 5   IncomeBand     300 non-null    object
 6   City           300 non-null    object
 7   RegionCode     300 non-null    object
 8   Persona        300 non-null    object
 9   RiskSegment    300 non-null    object
dtypes: int64(3), object(7)
memory usage: 23.6+ KB

In [5]:
customers['Persona'].value_counts()

Persona
family        91
grad          89
student       78
contractor    42
Name: count, dtype: int64

In [6]:
customers['RegionCode'].unique().tolist()

['E12000007',
 'E12000001',
 'E12000002',
 'E12000003',
 'S92000003',
 'N92000002',
 'E12000008',
 'W92000004',
 'E12000009',
 'E12000004',
 'E12000006',
 'E12000005']

In [7]:
customers['City'].unique().tolist()

['London',
 'Newcastle',
 'Manchester',
 'Leeds',
 'Edinburgh',
 'Belfast',
 'Reading',
 'Cardiff',
 'Brighton',
 'Bristol',
 'Nottingham',
 'Cambridge',
 'Birmingham']

In [8]:
customers.describe()

       CustomerID         Age  IncomeMonthly
count  300.000000  300.000000     300.000000
mean   150.500000   42.666667    2937.830000
std     86.746758   15.099078    1484.704669
min      1.000000   18.000000     871.000000
25%     75.750000   29.750000    1297.250000
50%    150.500000   42.000000    2454.500000
75%    225.250000   56.000000    4196.500000
max    300.000000   70.000000    6269.000000

In [9]:
customers['RiskSegment'].value_counts()

RiskSegment
Low       167
Medium     96
High       37
Name: count, dtype: int64

In [10]:
customers['IncomeBand'].value_counts()

IncomeBand
£4–8k        102
£0–1.5k       78
£1.5–2.5k     78
£2.5–4k       42
Name: count, dtype: int64